version: "3.7"
services:
    front:
        build:
            context: .
            dockerfile: Dockerfile.front
        ports:
            - 3000:3000
    back: 
        build : 
            context: .
            dockerfile: Dockerfile.back   
        ports:
            - 3004:3004 